# -*- coding: utf-8 -*-
"""Project UAS AI (Tic-Tac-Toe) - Haikal & Bayu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dlom8mLyB2VE0lAi0VydX4PmrsyVsR1V
"""

import random

# Fungsi untuk mencetak papan Tic-Tac-Toe
def cetak_papan(papan):
    for baris in papan:
        print(" | ".join(baris))
        print("-" * 5)

# Fungsi untuk memeriksa kemenangan
def cek_menang(papan, pemain):
    # Memeriksa baris, kolom, dan diagonal untuk kemenangan
    for i in range(3):
        if all([sel == pemain for sel in papan[i]]):  # Memeriksa baris
            return True
        if all([papan[j][i] == pemain for j in range(3)]):  # Memeriksa kolom
            return True
    if all([papan[i][i] == pemain for i in range(3)]):  # Memeriksa diagonal utama
        return True
    if all([papan[i][2 - i] == pemain for i in range(3)]):  # Memeriksa diagonal sekunder
        return True
    return False

# Fungsi untuk memeriksa seri
def cek_seri(papan):
    return all([sel in ['X', 'O'] for baris in papan for sel in baris])

# Fungsi untuk membuat gerakan
def buat_gerakan(papan, pemain, baris, kolom):
    if papan[baris][kolom] == ' ':
        papan[baris][kolom] = pemain
        return True
    else:
        print("Gerakan tidak sah! Sel sudah diisi.")
        return False

# Fungsi untuk bot membuat gerakan
def gerakan_bot(papan):
    pilihan = [(i, j) for i in range(3) for j in range(3) if papan[i][j] == ' ']
    baris, kolom = random.choice(pilihan)
    papan[baris][kolom] = 'O'

# Fungsi utama untuk memainkan permainan
def mainkan_permainan():
    papan = [[' ' for _ in range(3)] for _ in range(3)]
    pemain_saat_ini = 'X'
    while True:
        cetak_papan(papan)
        if pemain_saat_ini == 'X':
            print("Giliran pemain X:")
            baris = int(input("Masukkan baris (0, 1, atau 2): "))
            kolom = int(input("Masukkan kolom (0, 1, atau 2): "))
            if buat_gerakan(papan, pemain_saat_ini, baris, kolom):
                if cek_menang(papan, pemain_saat_ini):
                    cetak_papan(papan)
                    print("Pemain X menang!")
                    break
                elif cek_seri(papan):
                    cetak_papan(papan)
                    print("Permainan seri!")
                    break
                pemain_saat_ini = 'O'
        else:
            print("Giliran bot (O):")
            gerakan_bot(papan)
            if cek_menang(papan, 'O'):
                cetak_papan(papan)
                print("Bot menang!")
                break
            elif cek_seri(papan):
                cetak_papan(papan)
                print("Permainan seri!")
                break
            pemain_saat_ini = 'X'

mainkan_permainan()

mainkan_permainan()

